### ISSUE TITLE
package name?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test_reflective_loader#2]
The package is named `test_reflective_loader`, but it's not used to load reflective tests per se, but rather discover and define them. Perhaps rename the package to `test_reflective`? or `reflective_test`? `test_reflect`?

Similarly, the main method is called `runReflectiveTests`. Perhaps `defineReflectiveTests` or `discoverReflectiveTests`? The method is not running the tests itself, it's discovering and defining them.

**Comment by devoncarew** [comment]
@scheglov

**Comment by scheglov** [comment]
The name of the package was discussed between Seth, Natalie, Brian and other people through the yesterdays morning, and this is the compromise Seth suggested. I don't actually care.

Agree, `defineReflectiveTests` sounds better.

**Comment by scheglov** [comment]
https://github.com/dart-lang/test_reflective_loader/pull/4
