### ISSUE TITLE
package doesn't declare a dep on package:test

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test_reflective_loader#8]
But I think it should :)

@scheglov

**Comment by kevmoo** [comment]
You noticed! https://analyzer-dot-dartlang-pub.appspot.com/packages/test_reflective_loader/0.1.1/5656774724026368

**Comment by kevmoo** [comment]
Just move it from the dev dependency

**Comment by devoncarew** [comment]
Yup, I did see it from the relevancy score :)
